<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currency = array(
            array('id' => 1, 'country_id' => 1, 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani'),
            array('id' => 2, 'country_id' => 2, 'currency_code' => 'ALL', 'currency_name' => 'Albanian lek'),
            array('id' => 3, 'country_id' => 3, 'currency_code' => 'DZD', 'currency_name' => 'Algerian dinar'),
            array('id' => 4, 'country_id' => 4, 'currency_code' => 'USD', 'currency_name' => 'US dollar'),
            array('id' => 5, 'country_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 6, 'country_id' => 6, 'currency_code' => 'AOA', 'currency_name' => 'Angolan kwanza'),
            array('id' => 7, 'country_id' => 7, 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'),
            array('id' => 8, 'country_id' => 8, 'currency_code' => 'AAD', 'currency_name' => 'Antarctican dollar'),
            array('id' => 9, 'country_id' => 9, 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'),
            array('id' => 10, 'country_id' => 10, 'currency_code' => 'ARS', 'currency_name' => 'Argentine peso'),
            array('id' => 11, 'country_id' => 11, 'currency_code' => 'AMD', 'currency_name' => 'Armenian dram'),
            array('id' => 12, 'country_id' => 12, 'currency_code' => 'AWG', 'currency_name' => 'Aruban guilder'),
            array('id' => 13, 'country_id' => 13, 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'),
            array('id' => 14, 'country_id' => 14, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 15, 'country_id' => 15, 'currency_code' => 'AZN', 'currency_name' => 'New azerbaijani Manat'),
            array('id' => 16, 'country_id' => 16, 'currency_code' => 'BSD', 'currency_name' => 'Bahamian dollar'),
            array('id' => 17, 'country_id' => 17, 'currency_code' => 'BHD', 'currency_name' => 'Bahraini dinar'),
            array('id' => 18, 'country_id' => 18, 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi taka'),
            array('id' => 19, 'country_id' => 19, 'currency_code' => 'BBD', 'currency_name' => 'Barbados dollar'),
            array('id' => 20, 'country_id' => 20, 'currency_code' => 'BYN', 'currency_name' => 'Belarusian ruble'),
            array('id' => 21, 'country_id' => 21, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 22, 'country_id' => 22, 'currency_code' => 'BZD', 'currency_name' => 'Belize dollar'),
            array('id' => 23, 'country_id' => 23, 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO'),
            array('id' => 24, 'country_id' => 24, 'currency_code' => 'BMD', 'currency_name' => 'Bermudian dollar'),
            array('id' => 25, 'country_id' => 25, 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese ngultrum'),
            array('id' => 26, 'country_id' => 26, 'currency_code' => 'BOB', 'currency_name' => 'Boliviano'),
            array('id' => 27, 'country_id' => 27, 'currency_code' => 'BAM', 'currency_name' => 'Convertible mark'),
            array('id' => 28, 'country_id' => 28, 'currency_code' => 'BWP', 'currency_name' => 'Botswana pula'),
            array('id' => 29, 'country_id' => 29, 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'),
            array('id' => 30, 'country_id' => 30, 'currency_code' => 'BRL', 'currency_name' => 'Brazilian real'),
            array('id' => 31, 'country_id' => 31, 'currency_code' => 'GBP', 'currency_name' => 'Pound sterling'),
            array('id' => 32, 'country_id' => 32, 'currency_code' => 'BND', 'currency_name' => 'Brunei dollar'),
            array('id' => 33, 'country_id' => 33, 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian lev'),
            array('id' => 34, 'country_id' => 34, 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO'),
            array('id' => 35, 'country_id' => 35, 'currency_code' => 'BIF', 'currency_name' => 'Burundian franc'),
            array('id' => 36, 'country_id' => 36, 'currency_code' => 'KHR', 'currency_name' => 'Cambodian riel'),
            array('id' => 37, 'country_id' => 37, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 38, 'country_id' => 38, 'currency_code' => 'CAD', 'currency_name' => 'Canadian dollar'),
            array('id' => 39, 'country_id' => 39, 'currency_code' => 'CVE', 'currency_name' => 'Cape Verde escudo'),
            array('id' => 40, 'country_id' => 40, 'currency_code' => 'KYD', 'currency_name' => 'Cayman Islands dollar'),
            array('id' => 41, 'country_id' => 41, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 42, 'country_id' => 42, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 43, 'country_id' => 43, 'currency_code' => 'CLP', 'currency_name' => 'Chilean peso'),
            array('id' => 44, 'country_id' => 44, 'currency_code' => 'CNY', 'currency_name' => 'Chinese yuan renminbi (RMB)'),
            array('id' => 45, 'country_id' => 45, 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'),
            array('id' => 46, 'country_id' => 46, 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'),
            array('id' => 47, 'country_id' => 47, 'currency_code' => 'COP', 'currency_name' => 'Colombian peso'),
            array('id' => 48, 'country_id' => 48, 'currency_code' => 'KMF', 'currency_name' => 'Comoro franc'),
            array('id' => 49, 'country_id' => 49, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 50, 'country_id' => 50, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 51, 'country_id' => 51, 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'),
            array('id' => 52, 'country_id' => 52, 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican colon'),
            array('id' => 53, 'country_id' => 53, 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'),
            array('id' => 54, 'country_id' => 54, 'currency_code' => 'HRK', 'currency_name' => 'Croatian kuna'),
            array('id' => 55, 'country_id' => 55, 'currency_code' => 'CUC', 'currency_name' => 'Cuban convertible Peso'),
            array('id' => 56, 'country_id' => 56, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 57, 'country_id' => 57, 'currency_code' => 'CZK', 'currency_name' => 'Czech koruna'),
            array('id' => 58, 'country_id' => 58, 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'),
            array('id' => 59, 'country_id' => 59, 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian franc'),
            array('id' => 60, 'country_id' => 60, 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'),
            array('id' => 61, 'country_id' => 61, 'currency_code' => 'DOP', 'currency_name' => 'Dominican peso'),
            array('id' => 62, 'country_id' => 62, 'currency_code' => 'USD', 'currency_name' => 'US dollar'),
            array('id' => 63, 'country_id' => 63, 'currency_code' => 'USD', 'currency_name' => 'US dollar'),
            array('id' => 64, 'country_id' => 64, 'currency_code' => 'EGP', 'currency_name' => 'Egyptian pound'),
            array('id' => 65, 'country_id' => 65, 'currency_code' => 'SVC', 'currency_name' => 'Salvadoran colon'),
            array('id' => 66, 'country_id' => 66, 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'),
            array('id' => 67, 'country_id' => 67, 'currency_code' => 'ERN', 'currency_name' => 'Eritrean nakfa'),
            array('id' => 68, 'country_id' => 68, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 69, 'country_id' => 69, 'currency_code' => 'ETB', 'currency_name' => 'Ethipian birr'),
            array('id' => 70, 'country_id' => 70, 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'),
            array('id' => 71, 'country_id' => 71, 'currency_code' => 'FKP', 'currency_name' => 'Falkland Islands pound'),
            array('id' => 72, 'country_id' => 72, 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'),
            array('id' => 73, 'country_id' => 73, 'currency_code' => 'FJD', 'currency_name' => 'Fiji dollar'),
            array('id' => 74, 'country_id' => 74, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 75, 'country_id' => 75, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 76, 'country_id' => 76, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 77, 'country_id' => 77, 'currency_code' => 'XPF', 'currency_name' => 'French pacific franc'),
            array('id' => 78, 'country_id' => 78, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 79, 'country_id' => 79, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 80, 'country_id' => 80, 'currency_code' => 'GMD', 'currency_name' => 'Gambian dalasi'),
            array('id' => 81, 'country_id' => 81, 'currency_code' => 'GEL', 'currency_name' => 'Georgian lari'),
            array('id' => 82, 'country_id' => 82, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 83, 'country_id' => 83, 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi'),
            array('id' => 84, 'country_id' => 84, 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar pound'),
            array('id' => 85, 'country_id' => 85, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 86, 'country_id' => 86, 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'),
            array('id' => 87, 'country_id' => 87, 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'),
            array('id' => 88, 'country_id' => 88, 'currency_code' => 'EUR', 'currency_name' => 'Euro'),
            array('id' => 89, 'country_id' => 89, 'currency_code' => 'USD', 'currency_name' => 'US dollar'),
            array('id' => 90, 'country_id' => 90, 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan quetzal'),
            array('id' => 91, 'country_id' => 91, 'currency_code' => 'GGP', 'currency_name' => 'Guernsey Pound'),
            array('id' => 92, 'country_id' => 92, 'currency_code' => 'GNF', 'currency_name' => 'Guinean franc'),
            array('id' => 93, 'country_id' => 93, 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC'),
            array('id' => 94, 'country_id' => 94, 'currency_code' => 'GYD', 'currency_name' => 'Guyanese dollar'),
            array('id' => 95, 'country_id' => 95, 'currency_code' => 'HTG', 'currency_name' => 'Haitian gourde'),
            array('id' => 96, 'country_id' => 96, 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'),
            array('id' => 97, 'country_id' => 97, 'currency_code' => 'HNL', 'currency_name' => 'Honduran lempira'),
            array('id' => 98, 'country_id' => 98, 'currency_code' => 'HKD', 'currency_name' => 'Hong Kong dollar'),
            array('id' => 99, 'country_id' => 99, 'currency_code' => 'HUF', 'currency_name' => 'Hungarian forint'),
            array('id' => 100, 'country_id' => 100, 'currency_code' => 'ISK', 'currency_name' => 'Icelandic króna'),
            array('id' => 101, 'country_id' => 101, 'currency_code' => 'INR', 'currency_name' => 'Indian rupee'),


            array('id' => 229, 'country_id' => 229, 'currency_code' => 'AED', 'currency_name' => 'UAE dirham'),
            array('id' => 231, 'country_id' => 231, 'currency_code' => 'USD', 'currency_name' => 'US dollar'),
        );

        DB::table('currency_codes')->insert($currency);
    }
}
